<h1>numpy</h1>

<h2>Creating a numpy array</h2>

In [20]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(ax,id(ax),len(ax))

[1 2 3 4 5] 1919682816688 5


<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

In [10]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


<h2>Basic operations</h2>

In [11]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.50000000000001
19.500000000000004
3.8429155598321434


<h2>Multi-dimensional arrays</h2>

In [13]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)
print(ax.shape)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]
(3, 6)


<h3>Indexing</h3>

In [6]:
ax[1,3] #indexing

13.0

<h3>Slicing</h3>

In [7]:
ax[1:3,2:4]  # נרצה לשלוף שורות 1-2 ואת עמודות 2-3


array([[12., 13.],
       [22., 23.]])

In [8]:
ax[:,2:]

array([[ 2.,  3.,  4.,  5.],
       [12., 13., 14., 15.],
       [22., 23., 24., 25.]])

<h3>Reshaping</h3>


In [9]:
print(ax.shape)
ax.reshape(9,2)


(3, 6)


array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [20., 21.],
       [22., 23.],
       [24., 25.]])

In [10]:
print(ax.reshape(9,2))

[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [10. 11.]
 [12. 13.]
 [14. 15.]
 [20. 21.]
 [22. 23.]
 [24. 25.]]


In [11]:
ax.reshape(10,3)

ValueError: cannot reshape array of size 18 into shape (10,3)

<h3>Creating initialized arrays</h3>

In [12]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [12]:
ax = np.ones(10)
print(ax)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
bx = np.ones(10)
print(bx)
print(type(bx))

l = [1,2,3,4]
print(l)
print(type(l))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
<class 'list'>


In [51]:
ax = np.arange(10)**2
print(ax)

[ 0  1  4  9 16 25 36 49 64 81]


In [15]:
np.identity(10)  #מטריצת היחידה 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<h3>Matrix multiplication</h3>


In [24]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
#ay = ay*2

print(ay)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [25]:
print(ay.reshape(10,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [26]:
np.dot(ay,ay.reshape(10,2)) #Dot product

array([[220, 265],
       [220, 265]])

<h3>Comparing numpy arrays with lists</h3>

In [28]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print(ay)
np.dot(ax,ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


array([[ 15333, 120825],
       [120825, 978405]], dtype=int32)

### Comparing running time - np.arrays vs. lists

<h4>Functionalize this</h4>


In [6]:
np.arange(n)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [14]:
ay = [list(i) for i in zip(*ax)]
ay

# zip(*ay)

[[0, 0],
 [1, 1],
 [4, 8],
 [9, 27],
 [16, 64],
 [25, 125],
 [36, 216],
 [49, 343],
 [64, 512],
 [81, 729]]

In [29]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(1000000)    

datetime.timedelta(microseconds=2991)

<h4>Do the same with python lists</h4>


In [14]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)] #creates a lsit from each tuple created by the zip function
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(1000000)

datetime.timedelta(seconds=1, microseconds=313872)

In [18]:
x = [x**2 for x in range(10)]
y = [x**3 for x in range(10)]
ax = [x,y]
ax

[[0, 1, 4, 9, 16, 25, 36, 49, 64, 81],
 [0, 1, 8, 27, 64, 125, 216, 343, 512, 729]]

In [19]:
ay = [list(i) for i in zip(*ax)]
ay

[[0, 0],
 [1, 1],
 [4, 8],
 [9, 27],
 [16, 64],
 [25, 125],
 [36, 216],
 [49, 343],
 [64, 512],
 [81, 729]]

In [31]:
for n in [10,100,1000,10000,10000000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

10	0:00:00	0:00:00
100	0:00:00	0:00:00
1000	0:00:00	0:00:00
10000	0:00:00	0:00:00.005985
10000000	0:00:00.019650	0:00:14.048493


<h3>Selecting elements from an np array</h3>

In [27]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


In [28]:
np.where(ax%2==0)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 4, 0, 2, 4, 0, 2, 4], dtype=int64))

In [29]:
np.where(ax%2==0,1,0)

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [ ]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


<h3>Random number support in numpy</h3>

In [43]:
#print(np.random.normal(size=10))  # creates and array of 10 numbers, normally distributed with mean = 0 and sd = 1
#np.random.normal(size=(100,100)) 
#np.random.exponential(size=10) 
#np.random.exponential(1.0,size=(6,3)) 
np.random.randint(-10,10,size=(9,9)) # uniform distribution

array([[ -7,  -3,   8,   5,   5,   0,   3,  -5,   0],
       [  6,  -9,  -6,   5,  -8,  -3,   1,  -3,   2],
       [ -9,  -7,  -1,  -9,   6,   4,  -2,  -6,  -7],
       [ -3,   9,  -2,   1,  -9,  -6,   1,  -7,  -4],
       [  5,   8,  -8,  -9,   6,   5,   2,  -1,  -9],
       [ -4, -10,   9,   3,  -1,  -1,  -2,  -9,  -7],
       [ -5,   6,   6,  -9,  -8,   0,   5,  -7,   1],
       [  0,   2,   8,  -8,   7,   9,   4,  -6,  -2],
       [-10,  -8,  -1,   6,  -1,   8,  -3,  -6,   7]])

In [44]:
np.random.normal(size=100000).mean()

0.0009900426794362956